<a href="https://colab.research.google.com/github/Sourav61/Goeduhub-Assignments/blob/main/Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Author <a href = "https://github.com/Sourav61">Sourav Pahwa</a>
<br>ID: GO_STP_13420

<b> Assignment/Task 4
 <br> Question on Numpy</b>


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


<b>Q1)</b> Import the numpy package under the name np and Print the numpy version and the configuration? 

In [ ]:
import numpy as np
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


<b>Q2)</b> Create a null vector of size 10

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


<b>Q3)</b> Create Simple 1-D array and check type and check data types in array

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a)

print(type(a))

print(a.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


<b>Q4)</b> How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
x = np.array([[10, 20, 30],
              [40, 50, 60]])

print("The number of the given numpy array is: ",np.ndim)  

print("Size of the array: ", x.size)

print("Memory size of an element in bytes: ", x.itemsize)

print("Memory size used by numpy array in bytes:", x.size * x.itemsize)

The number of the given numpy array is:  <function ndim at 0x7f32b746d560>
Size of the array:  6
Memory size of an element in bytes:  8
Memory size used by numpy array in bytes: 48


<b>Q5)</b> Create a null vector of size 10 but the fifth value which is 1

In [ ]:
a = np.zeros(10)
print(a)
a[4]=1
print("After updating the 5th postion of original array with 1,now our nupy array becomes: \n",a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After updating the 5th postion of original array with 1,now our nupy array becomes: 
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


<b>Q6)</b> Create a vector with values ranging from 10 to 49

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


<b>Q7)</b> Reverse a vector (first element becomes last)

In [ ]:
a = np.arange(20)

print("The Numpy array created is: ",a)

print("The reversed vector(1-d numpy array) is: ",a[::-1])

The Numpy array created is:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The reversed vector(1-d numpy array) is:  [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


<b>Q8)</b> Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
a = np.arange(9)
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<b>Q9)</b> Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
nums = np.array([1,2,0,0,4,0])
print("Original array:")
print(nums)
print("Indices of elements equal to zero of the said array:")
for i in range(nums.size):
  if nums[i] != 0:
    print(nums[i], end=" ") 

Original array:
[1 2 0 0 4 0]
Indices of elements equal to zero of the said array:
1 2 4 

<b>Q10)</b> Create a 3x3 identity matrix

In [ ]:
print(np.ones(9).reshape(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<b>Q11)</b> Create a 3x3x3 array with random values

In [ ]:
a = np.random.random((3,3,3))
print(a)

[[[0.59706767 0.9386971  0.1055367 ]
  [0.50092591 0.46778236 0.04688149]
  [0.7431745  0.51572212 0.44310196]]

 [[0.77768537 0.13931581 0.66605149]
  [0.07849234 0.8043758  0.77449974]
  [0.50291669 0.99098981 0.68846193]]

 [[0.27516443 0.4007467  0.23463028]
  [0.6642409  0.30231542 0.91504537]
  [0.11786143 0.62288804 0.70190441]]]


<b>Q12)</b> Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
a = np.random.random((10,10))
print("The random numpy array generated is: \n",a)
print("The minimum value of random array generated is: ",a.min())
print("The maximum value of random array generated is: ",a.max())

The random numpy array generated is: 
 [[0.03420309 0.01672496 0.28553144 0.95797138 0.56261529 0.23208315
  0.83047402 0.49401682 0.6459628  0.00547783]
 [0.73293032 0.23824832 0.01349858 0.34184982 0.10333135 0.6612434
  0.64842409 0.88228225 0.42415946 0.53036432]
 [0.25301608 0.88323592 0.47811294 0.95610108 0.55468235 0.98618547
  0.00614637 0.54083859 0.61822645 0.05690923]
 [0.37751482 0.46936949 0.2242063  0.24320132 0.46779276 0.81999088
  0.81588768 0.98172245 0.75361509 0.58488951]
 [0.49823283 0.59154022 0.15582095 0.07095983 0.5341975  0.89097181
  0.99407967 0.97910082 0.48287099 0.81001598]
 [0.84650295 0.80063283 0.73424129 0.15473051 0.86644737 0.15663241
  0.6979614  0.2872118  0.95010592 0.10353785]
 [0.1780891  0.25919449 0.89388978 0.61571911 0.06471082 0.5543846
  0.55191734 0.35950144 0.07798711 0.93004301]
 [0.72801767 0.40338574 0.10334213 0.83995985 0.72262688 0.82487145
  0.41547107 0.79508502 0.91263965 0.42355395]
 [0.64908794 0.36105526 0.04867383 0.334806

<b>Q13)</b> Create a random vector of size 30 and find the mean value

In [ ]:
a = np.random.random(30)
a.mean()

0.5163323146521945

<b>Q14)</b> Create a 2d array with 1 on the border and 0 inside

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


<b>Q15)</b> How to add a border (filled with 0's) around an existing array? 

In [ ]:
x = np.ones((3,3))
print("Original array is: \n",x,"\n")

x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print("The required array is: \n",x)

Original array is: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

The required array is: 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


<b>Q16)</b> How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a[1,5],"\n")

print(a[0,:],"\n")

print(a[:,2],"\n")

print(a[0,:][1:6:2],"\n")

a[1,5]=20
print(a)

13 

[1 2 3 4 5 6 7] 

[ 3 10] 

[2 4 6] 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


<b>Q17)</b> How to Convert a 1D array to a 2D array with 2 rows

In [ ]:
a = np.zeros(4)
print("The one dimensional array used here is: ",a,"\n")
arr = a.reshape(2, 2)
print("The 2-D array produced from 1D array is: \n")
print(arr)

The one dimensional array used here is:  [0. 0. 0. 0.] 

The 2-D array produced from 1D array is: 

[[0. 0.]
 [0. 0.]]


<b>Q18)</b> Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

<b>Input:</b>

a = np.array([1,2,3])`

<b>Desired Output:</b>

# array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a=np.array([1,2,3])
print("The given array is: \n",a,"\n")
print("The required output is: \n",np.r_[np.repeat(a, 3), np.tile(a, 3)])

The given array is: 
 [1 2 3] 

The required output is: 
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


<b>Q19) Write a program to show how Numpy taking less memory compared to Python List?</b>

Ans) A nd-array in Numpy has faster computational speed and less memory required to complete a specific programs whereas a list takes a lot more memory in pyhton.

In [ ]:
l = range(10000)

import sys

a = 10
print(sys.getsizeof(a))

print(sys.getsizeof(a)*len(l))

a1 = np.arange(1000)
print(a1.size*a1.itemsize)

28
280000
8000


<b>Q20) Write a program to show how Numpy taking less time compared to Python List? </b>

Ans) A nd-array in Numpy has faster computational speed and less memory required to complete a specific programs whereas a list takes a lot more memory in pyhton.

In [ ]:
import time 
import sys

size = 1000000

a = range(size)
b = range(size)

#For pytho Lists
start = time.time()
result=  [(x+y) for x,y in zip(a,b)]
print((time.time()-start)*1000)

#For Numpy
start = time.time()
print((time.time()-start)*1000)

97.33891487121582
0.028133392333984375
